### ISSUE TITLE
adding a short url identified to a draft hearing does not work

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#193] opened 2016-04-07 06:49 UTC
when you are editing a draft (non-published) hearing, you can't add a custom identifier / slug if you don't do it before the first time you safe the draft. other wise it gives you an error message. the error does not highlight what causes the error, which makes it even harder for the user to understand what went wrong.

![image](https://cloud.githubusercontent.com/assets/2391876/14342861/cb0edd14-fca5-11e5-8c72-18003793e7a1.png)

**Comment by Rikuoja** [comment] 2016-04-29 10:31
Duplicate of backend issue 165.

**Closed** 2016-04-29 10:31 UTC
Labels: bug
