### ISSUE TITLE
dont ask for order info for hearing picture

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#187] opened 2016-04-07 05:54 UTC
even if i put "2" for the order of the hearing image it still shows on the top of the page on the hearing's page. this field should be hidden if it does not influence anything?

![image](https://cloud.githubusercontent.com/assets/2391876/14341898/1ce7595c-fc9e-11e5-8820-87f15433b676.png)

**Comment by Rikuoja** [comment] 2017-10-18 09:44
Backend admin issue.

**Comment by Rikuoja** [comment] 2017-10-18 09:45
Nope, it isn't! Image ordering should definitely be rethought along the lines of only displaying one image at top, and others in between the text as specified by the user.

**Comment by Rikuoja** [comment] 2018-01-05 11:12
Will be thought, duplicate of #452.

**Closed by Rikuoja** 2018-01-05 11:12 UTC
