### ISSUE TITLE
A better error message when trying to load a page that is not public (but a draft)

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#171] opened 2016-03-21 10:47 UTC
When you try to load a page (e.g. https://kerrokantasi.hel.fi/hearing/osallistuva_testi) through the link without the preview parameter (e.g. https://kerrokantasi.hel.fi/hearing/osallistuva_testi/?preview=d3oua7VC7mitm3SV8thO57WhoXp1oBr-bmfN0LJltgM), the pager gives an error message:
"API-kutsu beginFetchHearing epäonnistui: Error: Bad response from server. Kokeile pian uudelleen." and does not load.

This msg should rather tell the user to sign in, if they want to view the page, as it is not public at the moment.

**Comment by Rikuoja** [comment] 2017-10-18 09:42
Duplicate of #316

**Closed by Rikuoja** 2017-10-18 09:42 UTC
