### ISSUE TITLE
IE11: scrolling causes top menu to appear and disappear

### ISSUE THREAD

**Issue by vikoivun** [City-of-Helsinki/kerrokantasi-ui#220] opened 2016-06-09 08:48 UTC
Problem: While scrolling using IE11 the top menu toggles in and out of existence.

Expected behaviour: menu bar shrinks when starting to scroll from top and stays minified but visible thereafter

Platform: IE11 on Windows 7 (modern.ie virtual machine)

**Comment by Rikuoja** [comment] 2017-10-18 09:51
Probably linked to #409 .

**Comment by Rikuoja** [comment] 2017-10-18 09:51
Oops, not closed.

**Comment by Rikuoja** [comment] 2018-01-05 11:11
Duplicate of #409.

**Closed by Rikuoja** 2018-01-05 11:11 UTC
