### ISSUE TITLE
Fix left arrow button not working in hearing navigation

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#582] opened 2018-02-07 13:04 UTC
If hearing has less than 6 subsections, the left button does not work.

**Comment by Rikuoja** [comment] 2018-02-07 13:23
Yet another duplicate of https://github.com/City-of-Helsinki/kerrokantasi-ui/issues/574 :)

**Closed by Rikuoja** 2018-02-07 13:23 UTC
Labels: bug

**Comment by petterill** [comment] 2018-02-07 13:24
damn
