### ISSUE TITLE
X/Close does not close hearing editor popup

### ISSUE THREAD

**Issue by petterill** [City-of-Helsinki/kerrokantasi-ui#462] opened 2017-11-16 13:48 UTC

**Comment by petterill** [comment] 2017-11-16 13:49
currently no way to cancel if already started to create a hearing

**Comment by Rikuoja** [comment] 2017-11-16 13:53
Works for me. Which browser are you using?

**Comment by petterill** [comment] 2017-11-16 13:56
Chrome 61.0.3163.100 on win10 enterprise

**Comment by jonnetanninen** [comment] 2017-11-17 14:20
Can't reproduce, could this be because most of the X button was left under the navigation bar if the page was scrolled down before opening the editor?

**Comment by Rikuoja** [comment] 2017-11-21 14:35
I managed to reproduce this. On kerrokantasi.hel.ninja, after scrolling the map around in an existing hearing, trying to close the window resulted in the minified react error
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `t`
```

Then, clicking another button on the editor will belatedly close the hearing.

**Comment by Rikuoja** [comment] 2017-11-21 14:35
So could this have something to do with react-leaflet?

**Comment by jonnetanninen** [comment] 2017-11-21 14:43
Yes, got it now. This was probably due to wrong use of <GeoJSON /> element as it was formerly used as <GeoJson />. Should be fixed in next PR.

**Closed** 2017-12-12 14:50 UTC
Labels: Admin UI, in progress
