### ISSUE TITLE
dont show "hearing closed" box when its a preview of a hearing that is opening in the future

### ISSUE THREAD

**Issue by joonasp** [City-of-Helsinki/kerrokantasi-ui#188] opened 2016-04-07 05:58 UTC
![image](https://cloud.githubusercontent.com/assets/2391876/14341959/c4c0d2b6-fc9e-11e5-81a9-d7f3622ca59f.png)

**Comment by Rikuoja** [comment] 2017-10-18 09:46
Duplicate of #210

**Closed by Rikuoja** 2017-10-18 09:46 UTC
